run_plot_ll<-function(rnd=rnd,pgr_rb=pgr_rb,pgr_sm=pgr_sm){
#run_model(rnd=rnd,pgr_rb=pgr_rb,pgr_sm=pgr_sm)
#a<-ant(rnd=rnd,pgr_rb=pgr_rb,pgr_sm=pgr_sm)
#aa0<-inlineleafmap(year=2008)
output <- plotr_leaflet(year=2008)
#library(RJSONIO)
#a0<-paste(capture.output(aa), collapse ='\n')
#a3<-tags$html(a)
#
#as<-HTML(aa0)
#aa<-paste(capture.output(as), collapse ='\n')
#a2<-gsub("\"", "'", aa, fixed=TRUE)
#aa2<-gsub("\r", "", aa, fixed=TRUE)
#a<-gsub("\n", "", aa2, fixed=TRUE)
#paste(aa2)
#return(aa)
#aa0
library(htmltools)
library(htmlwidgets)
#save_html(output,'x.html')
saveWidget(output,'x.html')
x2<-includeHTML('x.html')
#b<-leafletOutput(output)
#b<-HTML(output)
#k<-tags$html(output)
#kk<-gsub('<div id="htmlwidget-6899" style="width:100%;height:400px;" class="leaflet"></div>','', k, fixed=TRUE)
#kk2<-gsub('</html>','', kk, fixed=TRUE)
#a<-toJSON(output)
#aa<-tags$html(output) # 
#a1a<-gsub('<html>','<html><body>', aa, fixed=TRUE)
#a2a<-gsub('</html>','</body></html>', a1a, fixed=TRUE)
kk<-paste(capture.output(x2),collapse='\n')
return(kk)
}
